USE COLIBRI

ALTER TABLE dbo.Bitacora_Usuarios_RRHH DROP CONSTRAINT CK_BitRR_accion;
GO

ALTER TABLE dbo.Bitacora_Usuarios_RRHH ADD CONSTRAINT CK_BitRR_accion
    CHECK (accion IN ('INSERT','UPDATE','DELETE','ACTIVACION','DESACTIVACION','PASSWORD_CHANGE','ROLE_ASSIGNMENT','ASIGNACION_MESA'));
GO
