CREATE TABLE dbo.nomina_mensual (
    id INT IDENTITY(1,1) NOT NULL,
    empleado_id INT NOT NULL,
    mes INT NOT NULL,
    anio INT NOT NULL,
    horas_trabajadas DECIMAL(10,2) NOT NULL DEFAULT 0,
    horas_extra DECIMAL(10,2) NOT NULL DEFAULT 0,
    vacaciones_pagadas DECIMAL(5,2) NOT NULL DEFAULT 0,
    dias_trabajados INT NOT NULL DEFAULT 0,
    dias_ausentes INT NOT NULL DEFAULT 0,
    salario_base DECIMAL(18,2) NOT NULL DEFAULT 0,
    monto_horas_extra DECIMAL(18,2) NOT NULL DEFAULT 0,
    bonificaciones DECIMAL(18,2) NOT NULL DEFAULT 0,
    deducciones DECIMAL(18,2) NOT NULL DEFAULT 0,
    salario_bruto DECIMAL(18,2) NOT NULL DEFAULT 0,
    salario_neto DECIMAL(18,2) NOT NULL DEFAULT 0,
    estado NVARCHAR(20) NOT NULL DEFAULT 'pendiente',
    fecha_cierre DATETIME NULL,
    observaciones NVARCHAR(500) NULL,
    creado_por INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_nomina_mensual PRIMARY KEY CLUSTERED (id),
    CONSTRAINT FK_nomina_mensual_empleado FOREIGN KEY (empleado_id) REFERENCES dbo.Empleados(id_empleado)
);
